# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Andrei Rosseti"
description: > # this means to ignore newlines until "email:"
  Eu inspiro e capacito pessoas no desenvolvimento de software! Lets grow together! 🚀💻 #softwaredeveloper #crypto #blockchain

# email: andrei@facedigital.com.br
#blog logo
logo: "/assets/images/ar_logo.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/galaxy-3608029_1920.jpg"

name: 'Andrei Rosseti'
author: 'Andrei Rosseti'
author_image: "/assets/images/author.png"

paginate:	5

url: "https://rosseti.github.io" 
baseurl: ""
#used to display twitter cards
twitter_handle: '@andreirosseti'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: G-KTXXSHGKRP

# social icons and sharing options
social:
  - icon:	link
    url:	https://middlex.com.br/andrei/
    desc: Projetos
    share_url: https://middlex.com.br/andrei/
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	twitter
    url:	https://twitter.com/andreirosseti
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/andrei.rosseti
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
  
  - icon:	instagram
    url:	https://instagram.com/andreirosseti

  - icon:	github
    url:	https://github.com/rosseti
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
